name: AutoUpdatePages

on:
  push:
    branches:
      - master
    paths:
      - "src/**"
jobs:
  build-and-update-pages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12]
    steps:
      - name: build
        run: |
          npm i
          npm run build
      - name: update
        uses: JamesIves/github-pages-deploy-action@3.5.2
        with:
          branch: gh-pages
          folder: test_app
